sudo: required

language: node_js
node_js:
    - "12"

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - docker info
  - docker build -t jenkins-ssh-agent .
  - docker images